version: "3"
services:
  db:
    image: mysql:5.7
    container_name: dbmu1
    restart: always
    ports:
    - "3306:3306"
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: main01
      MYSQL_ROOT_PASSWORD: main01
    volumes:
      - ./data:/var/lib/mysql

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    links:
      - db